spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 7001
spring: 
  profiles: dev
  application: 
    name:microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: www.eureka7001.com
  client: 
    register-with-eureka: false #当前的eureka-server自己不向自己注册服务
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://www.eureka7001.com:7001/eureka
---

server:
  port: 7001
spring: 
  profiles: test
  application: 
    name:microservicecloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: www.eureka7001.com
  client: 
    register-with-eureka: false #当前的eureka-server自己不向自己注册服务
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://www.eureka7001.com:7001/eureka